name: Automation Test
on:
  push:
    branches:
      - "master"
    pull_request:
      branches:
        - "master"
  workflow_dispatch:
    inputs:
      executeTags:
        description: 'Create User'
        required: true
        default: '@auto-createuser'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.9
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 11
      - name: Cache the Maven packages to speed up build
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ env.cache-name }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-${{ env.cache-name }}-
            ${{ runner.os }}-maven-
            ${{ runner.os }}-
      - name: Imprimir
        run: |
          echo ${{github.event_name}}

      - if: ${{ github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'master' }}
        name: Unit and Integration Tests by default fixture
        run: mvn clean verify -Dcucumber.filter.tags=auto-createuser

      - if: ${{ github.event_name == 'workflow_dispatch' }}
        name: Unit and Integration Tests by workflow_dispatch
        run: mvn clean verify -Dcucumber.filter.tags=${{ github.event.inputs.executeTags }}

      - name: Upload Results
        uses: actions/upload-artifact@v2
        with:
          name: TestResults
          path: |
            ./target/site/serenity/
