name: Automation Test
on:
  push:
    branches:
      - "master"
    pull_request:
      branches:
        - "master"

  workflow_dispatch:
    inputs:
      executeTags:
        description: 'Create User'
        required: true
        default: '@auto-createuser'
env:
  MAVEN_OPTS: "-Dmaven.repo.local=${{ github.workspace }}/repository"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2.3.1
        with:
          distribution: 'adopt'
          java-version: 11
      #    cache: 'maven'
      - name: Cache maven modules
        uses: actions/cache@v2
        env:
          cache-name: cache-maven-modules
        with:
       #   path: ${{ github.workspace }}/repository
          path: ~/.m2/repository
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/pom.xml') }}
          #restore-keys: |
           # ${{ runner.os }}-maven-
      - name: Imprimir
        run: |
          echo ${{github.event_name}}

      - if: ${{ github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'master' }}
        name: Unit and Integration Tests by default fixture
        run: mvn clean verify -Dcucumber.filter.tags=auto-createuser

      - if: ${{ github.event_name == 'workflow_dispatch' }}
        name: Unit and Integration Tests by workflow_dispatch
        run: mvn clean verify -Dcucumber.filter.tags=${{ github.event.inputs.executeTags }}

      - name: Upload Results
        uses: actions/upload-artifact@v2
        with:
          name: TestResults
          path: |
            ./target/site/serenity/


