name: Automation Test
on:
  push:
    branches:
      - "master"
  pull_request:
      branches:
        - "master"

  workflow_dispatch:
    inputs:
      executeTags:
        description: 'Create User'
        required: true
        default: '@auto-createuser'
env:
  MAVEN_OPTS: "-Dmaven.repo.local=${{ github.workspace }}/repository"
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MAVEN_OPTS: -Xmx1024M
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11
      - name: Build Maven project
        run: mvn -B package --file pom.xml
      - name: Cache the Maven packages
        id: myCacheMaven
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-v1-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-v1

      - if: steps.myCacheMaven.outputs.cache-hit != 'true'
        name: Install Dependenciesss
        run: mvn install
      


      - if: ${{ github.event_name == 'push' }}
        #&& github.event.pull_request.base.ref == 'master'
        name: Unit and Integration Tests by default fixture
        run: mvn clean install -Dcucumber.filter.tags=@auto-createuser --file pom.xml

      - if: ${{ github.event_name == 'workflow_dispatch' }}
        name: Unit and Integration Tests by workflow_dispatch
        run: mvn clean install -Dcucumber.filter.tags=${{ github.event.inputs.executeTags }} --file pom.xml

      - name: Upload Results
        uses: actions/upload-artifact@v2
        with:
          name: TestResults
          path: |
            ./target/site/serenity/


